import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from 'next/link'
import Navbar  from './components/navbar'
import Footer from './components/footer'




const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "HELLO",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar/>  {/* component call*/}
        {children}
        <Footer/> {/* component call*/}
 
        {/*<div>
              <nav className="flex space-x-4">
                <Link href="/">Home</Link>
                <Link href="/signup">Signup</Link>
                <Link href="/login">Login</Link>
              </nav> 

        </div>*/}
      </body>
    </html>
  );
}
